const express=require('express');
const http=require('http');
const path=require('path');
const crypto=require('crypto');
const multer=require('multer');
const XLSX=require('xlsx');
const {Server}=require('socket.io');
const {Pool}=require('pg');
const app=express(), server=http.createServer(app), io=new Server(server);
const PORT=process.env.PORT||3000;
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
const mem={t:null,rounds:new Map(),tables:new Map(),phones:new Map()};
const id=p=>p+'_'+crypto.randomBytes(9).toString('hex');
async function init(){if(!pool){console.log('No DATABASE_URL: temporary memory mode');return}await pool.query(`CREATE TABLE IF NOT EXISTS tournaments(id TEXT PRIMARY KEY,name TEXT NOT NULL,year INTEGER,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ DEFAULT NOW(),ended_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS rounds(id TEXT PRIMARY KEY,tournament_id TEXT REFERENCES tournaments(id) ON DELETE CASCADE,round_number INTEGER,source_filename TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(tournament_id,round_number));CREATE TABLE IF NOT EXISTS tables_protocols(id TEXT PRIMARY KEY,round_id TEXT REFERENCES rounds(id) ON DELETE CASCADE,table_number INTEGER,player1 TEXT,player2 TEXT,games JSONB DEFAULT '[0,0,0,0,0,0,0]'::jsonb,score1 INTEGER DEFAULT 0,score2 INTEGER DEFAULT 0,stose1 INTEGER DEFAULT 0,stose2 INTEGER DEFAULT 0,status TEXT DEFAULT 'open',result_command INTEGER,updated_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(round_id,table_number));CREATE TABLE IF NOT EXISTS phone_sessions(token TEXT PRIMARY KEY,tournament_id TEXT REFERENCES tournaments(id) ON DELETE CASCADE,table_protocol_id TEXT REFERENCES tables_protocols(id) ON DELETE CASCADE,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),revoked_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS annual_stose(id BIGSERIAL PRIMARY KEY,year INTEGER,player_name TEXT,total INTEGER DEFAULT 0,UNIQUE(year,player_name));`)}
function scores(g){return[g.filter(x=>x===1).length,g.filter(x=>x===2).length]}
function valid(g){let[a,b]=scores(g);return(a===3&&b===3)||(a>=4&&b<=3)||(b>=4&&a<=3)}
function command(g){if(!valid(g))return null;let[a,b]=scores(g);return a===3&&b===3?3:a>b?1:2}
function parseExcel(wb){const sh=wb.Sheets.EKSPORT;if(!sh)throw Error('Excel failā nav lapas EKSPORT.');const rows=XLSX.utils.sheet_to_json(sh,{header:1,defval:''});const hi=rows.findIndex(r=>r.some(c=>String(c).trim().toLowerCase()==='galds'));if(hi<0)throw Error('EKSPORT lapā nav kolonnas Galds.');const h=rows[hi].map(String),ti=h.findIndex(x=>x.trim().toLowerCase()==='galds'),out=new Map();for(let i=hi+1;i<rows.length;i++){let r=rows[i],n=Number(r[ti]);if(!Number.isFinite(n)||n<=0)continue;let p1=String(r[2]||'').trim(),p2=String(r[8]||'').trim();if(!p1||!p2){let c=r.map(x=>String(x).trim()).filter(Boolean).filter(x=>x!==String(r[ti]));p1=p1||c[0]||'';p2=p2||c[1]||''}if(p1&&p2&&!out.has(n))out.set(n,{tableNumber:n,player1:p1,player2:p2})}return[...out.values()].sort((a,b)=>a.tableNumber-b.tableNumber)}
async function tournament(){if(pool){let r=await pool.query("SELECT * FROM tournaments WHERE status='active' ORDER BY created_at DESC LIMIT 1");return r.rows[0]||null}return mem.t}
function norm(r){return{id:r.id||r.protocol_id,roundId:r.round_id,tableNumber:+r.table_number,player1:r.player1,player2:r.player2,games:r.games||[0,0,0,0,0,0,0],score1:+(r.score1||0),score2:+(r.score2||0),stose1:+(r.stose1||0),stose2:+(r.stose2||0),status:r.status||'open',resultCommand:r.result_command==null?null:+r.result_command}}
async function current(t){if(pool){let r=await pool.query(`SELECT r.id,r.round_number,r.source_filename,tp.* FROM rounds r JOIN tables_protocols tp ON tp.round_id=r.id WHERE r.tournament_id=$1 ORDER BY r.round_number DESC,tp.table_number`,[t.id]);if(!r.rows.length)return{round:null,tables:[]};let rid=r.rows[0].id;return{round:{id:rid,roundNumber:r.rows[0].round_number,sourceFilename:r.rows[0].source_filename},tables:r.rows.filter(x=>x.id===rid).map(norm)}}let rs=[...mem.rounds.values()].filter(x=>x.tournamentId===t.id).sort((a,b)=>b.roundNumber-a.roundNumber);if(!rs.length)return{round:null,tables:[]};let r=rs[0];return{round:{id:r.id,roundNumber:r.roundNumber,sourceFilename:r.sourceFilename},tables:[...r.tables.values()].sort((a,b)=>a.tableNumber-b.tableNumber)}}
async function protocol(pid){if(pool){let r=await pool.query('SELECT * FROM tables_protocols WHERE id=$1',[pid]);return r.rows[0]?norm(r.rows[0]):null}return mem.tables.get(pid)||null}
async function save(p){[p.score1,p.score2]=scores(p.games);p.resultCommand=command(p.games);p.status=p.resultCommand?'finished':'open';if(pool)await pool.query('UPDATE tables_protocols SET games=$2,score1=$3,score2=$4,stose1=$5,stose2=$6,status=$7,result_command=$8,updated_at=NOW() WHERE id=$1',[p.id,JSON.stringify(p.games),p.score1,p.score2,p.stose1,p.stose2,p.status,p.resultCommand]);return p}
app.get('/api/health',(q,s)=>s.json({ok:true,app:'novuss-digital-protocol',database:!!pool}));
app.post('/api/tournaments',async(q,s)=>{try{if(await tournament())return s.status(409).json({error:'Aktīvs turnīrs jau pastāv.'});let t={id:id('t'),name:q.body.name||'Novusa turnīrs',year:+q.body.year||new Date().getFullYear(),status:'active'};if(pool)await pool.query('INSERT INTO tournaments(id,name,year) VALUES($1,$2,$3)',[t.id,t.name,t.year]);else mem.t=t;s.json(t)}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/tournament',async(q,s)=>{try{let t=await tournament();let c=t?await current(t):{round:null,tables:[]};s.json({tournament:t,...c})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/rounds/import',upload.single('excel'),async(q,s)=>{try{if(!q.file)return s.status(400).json({error:'Nav pievienots Excel fails.'});let t=await tournament();if(!t){t={id:id('t'),name:'Novusa turnīrs',year:new Date().getFullYear(),status:'active'};if(pool)await pool.query('INSERT INTO tournaments(id,name,year) VALUES($1,$2,$3)',[t.id,t.name,t.year]);else mem.t=t}let tables=parseExcel(XLSX.read(q.file.buffer,{type:'buffer'})),c=await current(t),rn=c.round?c.round.roundNumber+1:1,rid=id('r');if(pool){await pool.query('INSERT INTO rounds(id,tournament_id,round_number,source_filename) VALUES($1,$2,$3,$4)',[rid,t.id,rn,q.file.originalname]);for(const x of tables)await pool.query('INSERT INTO tables_protocols(id,round_id,table_number,player1,player2) VALUES($1,$2,$3,$4,$5)',[id('tp'),rid,x.tableNumber,x.player1,x.player2])}else{let r={id:rid,tournamentId:t.id,roundNumber:rn,sourceFilename:q.file.originalname,tables:new Map()};mem.rounds.set(rid,r);for(const x of tables){let p={id:id('tp'),roundId:rid,tableNumber:x.tableNumber,player1:x.player1,player2:x.player2,games:[0,0,0,0,0,0,0],score1:0,score2:0,stose1:0,stose2:0,status:'open',resultCommand:null};r.tables.set(x.tableNumber,p);mem.tables.set(p.id,p)}}let data=await current(t);io.emit('round-imported',data);s.json({ok:true,roundNumber:rn,tables})}catch(e){console.error(e);s.status(500).json({error:e.message})}});
app.get('/api/table/:id',async(q,s)=>{try{let p=await protocol(q.params.id);p?s.json(p):s.status(404).json({error:'Galds nav atrasts.'})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/table/:id/game',async(q,s)=>{try{let p=await protocol(q.params.id),g=+q.body.game,w=+q.body.winner;if(!p)return s.status(404).json({error:'Galds nav atrasts.'});if(!Number.isInteger(g)||g<0||g>6||![0,1,2].includes(w))return s.status(400).json({error:'Nederīgi dati.'});p.games[g]=w;await save(p);io.emit('protocol-updated',p);s.json(p)}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/table/:id/stose',async(q,s)=>{try{let p=await protocol(q.params.id),pl=+q.body.player,d=+q.body.delta;if(!p)return s.status(404).json({error:'Galds nav atrasts.'});if(![1,2].includes(pl)||![-1,1].includes(d))return s.status(400).json({error:'Nederīgi ŠTOSE dati.'});let k=pl===1?'stose1':'stose2';p[k]=Math.max(0,p[k]+d);await save(p);io.emit('protocol-updated',p);s.json(p)}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/table/:id/finish',async(q,s)=>{try{let p=await protocol(q.params.id);if(!p)return s.status(404).json({error:'Galds nav atrasts.'});if(!valid(p.games))return s.status(400).json({error:'Šo rezultātu vēl nevar pabeigt.'});await save(p);io.emit('protocol-finished',p);s.json(p)}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/phone-token',async(q,s)=>{try{let t=await tournament(),p=await protocol(q.body.protocolId);if(!t)return s.status(400).json({error:'Nav aktīva turnīra.'});if(!p)return s.status(404).json({error:'Galds nav atrasts.'});let token=crypto.randomBytes(18).toString('base64url');if(pool)await pool.query('INSERT INTO phone_sessions(token,tournament_id,table_protocol_id) VALUES($1,$2,$3)',[token,t.id,p.id]);else mem.phones.set(token,{token,tournamentId:t.id,tableProtocolId:p.id,active:true});s.json({token,url:'/table.html?token='+encodeURIComponent(token)})}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/phone/:token',async(q,s)=>{try{let x;if(pool){let r=await pool.query('SELECT * FROM phone_sessions WHERE token=$1 AND active=TRUE',[q.params.token]);x=r.rows[0]}else x=mem.phones.get(q.params.token);if(!x||x.active===false)return s.status(403).json({error:'Šī telefona piekļuve vairs nav aktīva.'});let p=await protocol(x.table_protocol_id||x.tableProtocolId);p?s.json({session:x,protocol:p}):s.status(404).json({error:'Galds nav atrasts.'})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/tournament/end',async(q,s)=>{try{let t=await tournament();if(!t)return s.status(404).json({error:'Nav aktīva turnīra.'});if(pool){await pool.query("UPDATE tournaments SET status='ended',ended_at=NOW() WHERE id=$1",[t.id]);await pool.query('UPDATE phone_sessions SET active=FALSE,revoked_at=NOW() WHERE tournament_id=$1',[t.id])}else{t.status='ended';for(const x of mem.phones.values())if(x.tournamentId===t.id)x.active=false}io.emit('tournament-ended',{tournamentId:t.id});s.json({ok:true})}catch(e){s.status(500).json({error:e.message})}});
app.get('/admin',(q,s)=>s.sendFile(path.join(__dirname,'public','admin.html')));app.get('/table.html',(q,s)=>s.sendFile(path.join(__dirname,'public','table.html')));
init().then(()=>server.listen(PORT,()=>console.log('Novuss server listening on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
